services:
  my-mvc-web:
    image: pseuder/dntnetmvc_demo1:latest
    container_name: dntnetmvc_demo1_container
    restart: always
    ports:
      - "5006:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production